stages:
  - lint
variables:
  TERRAFORM_VERSION: 0.12.24
  TFLINT_VERSION: 0.15.5
tflint:
  stage: lint
  image:
    name: hashicorp/terraform:${TERRAFORM_VERSION}
    entrypoint: [""]
  before_script:
    - wget https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip -O tflint.zip
    - unzip tflint.zip -d $HOME
    - rm tflint.zip
  script:
    - >-
      find . -type f -name "*.tf" -exec dirname {} \;
      | sort -u
      | while read line; do
          cd $line;
          echo "processing $PWD ..."
          terraform init -backend=false && $HOME/tflint --config ${CI_PROJECT_DIR}/.tflint.hcl;
          cd -;
        done
